# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_manage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 551)
        Dialog.setMinimumSize(QtCore.QSize(371, 551))
        Dialog.setMaximumSize(QtCore.QSize(371, 551))
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 351, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 51))
        self.groupBox.setObjectName("groupBox")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 20, 21, 20))
        self.label.setObjectName("label")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(120, 20, 81, 22))
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(210, 20, 61, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(280, 20, 61, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 351, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 191, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(210, 20, 61, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 20, 61, 23))
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.dateEdit, self.dateEdit_2)
        Dialog.setTabOrder(self.dateEdit_2, self.pushButton_9)
        Dialog.setTabOrder(self.pushButton_9, self.pushButton_10)
        Dialog.setTabOrder(self.pushButton_10, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.tableWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "数据管理"))
        self.groupBox.setTitle(_translate("Dialog", "日期选择"))
        self.label.setText(_translate("Dialog", "至"))
        self.pushButton_9.setText(_translate("Dialog", "今天"))
        self.pushButton_10.setText(_translate("Dialog", "本周"))
        self.groupBox_2.setTitle(_translate("Dialog", "查找"))
        self.comboBox.setItemText(0, _translate("Dialog", "默认"))
        self.pushButton_8.setText(_translate("Dialog", "查找"))
