# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_show_message(object):
    def setupUi(self, Dialog_show_message):
        Dialog_show_message.setObjectName("Dialog_show_message")
        Dialog_show_message.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_show_message.resize(320, 240)
        self.pushButton = QtWidgets.QPushButton(Dialog_show_message)
        self.pushButton.setGeometry(QtCore.QRect(110, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog_show_message)
        self.label.setGeometry(QtCore.QRect(30, 70, 261, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_show_message)
        QtCore.QMetaObject.connectSlotsByName(Dialog_show_message)

    def retranslateUi(self, Dialog_show_message):
        _translate = QtCore.QCoreApplication.translate
        Dialog_show_message.setWindowTitle(_translate("Dialog_show_message", "提示"))
        self.pushButton.setText(_translate("Dialog_show_message", "确定"))
